load_paths:
  - lib/assets/javascripts
  - lib/assets/stylesheets
  - test/javascripts/
  - turbolinks-source: lib/assets/javascripts
  - jquery-rails: vendor/assets/javascripts
  - lodash-rails: vendor/assets/javascripts
  - tao_on_rails:
    - lib/assets/javascripts
    - lib/assets/stylesheets
    - vendor/assets/javascripts
    - vendor/assets/stylesheets
  - tao_ui:
    - lib/assets/javascripts
    - lib/assets/stylesheets
    - vendor/assets/javascripts
    - vendor/assets/stylesheets

logical_paths:
  - tao.js
  - tao.css
  - tao/ui.js
  - tao/ui.css
  - tao_popover.css
  - tao_popover.js
  - tao_popover_test.js

build:
  logical_paths:
    - tao.js
    - tao.css
    - tao/ui.js
    - tao/ui.css
    - tao_popover.css
    - tao_popover.js
  path: dist

plugins:
  sauce_labs:
    tunnel_timeout: 120
    tunnel_args:
      - '-B'
      - 'all'
    browsers:
      Google Chrome:
        os: Mac, Windows
        version: -1
      Firefox:
        os: Mac, Windows
        version: -1
      Safari:
        platform: Mac
        version: -1
      iPhone:
        version: [9.3]
      Motorola Droid 4 Emulator:
        version: [5.1, 4.4]
